export ZSH=$HOME/.oh-my-zsh
export ZPLUG_HOME=/usr/local/opt/zplug

ZSH_THEME="gentoo"

plugins=(git vi kubectl fzf)

source $ZSH/oh-my-zsh.sh
source ~/git-repos/kube-ps1/kube-ps1.sh
source $ZPLUG_HOME/init.zsh

zplug "changyuheng/fz", defer:1
zplug "rupa/z", use:z.sh
autoload -Uz colors; colors

PROMPT='$(kube_ps1)'$PROMPT

bindkey -v

# Appends every command to the history file once it is executed
HISTSIZE=50000
SAVEHIST=50000
setopt inc_append_history
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
# # Reloads the history whenever you use it
setopt SHARE_HISTORY

ulimit -n 4096
setopt CDABLE_VARS
setopt rm_star_silent

SSHAGENT=/usr/bin/ssh-agent
SSHAGENTARGS="-s"
if [ -z "$SSH_AUTH_SOCK" -a -x "$SSHAGENT" ]; then
    eval `$SSHAGENT $SSHAGENTARGS`
    trap "kill $SSH_AGENT_PID" 0
fi

if [ -d $HOME/.zsh_conf ]; then
	for file in $HOME/.zsh_conf/*.zsh; do
		source $file
	done
fi

if [ -d $HOME/git-repos/.file/zshrc/ ]; then
	for file in $HOME/git-repos/.file/zshrc/*.zsh; do
		source $file
	done
fi

source ~/git-repos/kubectl-fzf/kubectl_fzf.plugin.zsh
#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
zplug load
