export HISTFILE=~/.zistory
export HISTSIZE=2000000

export ZPLUG_HOME=$HOME/git-repos/zplug
source $ZPLUG_HOME/init.zsh

zplug "plugins/fzf", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/docker", from:oh-my-zsh
#
# Machine specific configuration files
if [ -d $HOME/.zsh_conf ]; then
    zplug "$HOME/.zsh_conf", from:local
fi
zplug "~/git-repos/.file/zplug/misc", from:local
zplug "~/git-repos/.file/zplug/theme", from:local, as:theme
zplug "~/git-repos/.file/zplug/kube", from:local, defer:3
zplug "~/git-repos/.file/zplug/gcloud", from:local

zplug "~/git-repos/.file/zplug/linux", from:local, if:"[[ $OSTYPE == *linux* ]]"
zplug "~/git-repos/.file/zplug/mac", from:local, if:"[[ $OSTYPE == *darwin* ]]"

zplug "seebi/dircolors-solarized"
zplug "changyuheng/fz"
zplug "rupa/z", use:z.sh

zplug "plugins/kubectl", from:oh-my-zsh, defer:2
zplug "~/git-repos/kubectl-fzf", from:local, defer:3

ulimit -n 4096

[ -z "$SSH_TTY" ] && keychain id_rsa -q
[ -z "$HOSTNAME" ] && HOSTNAME=`uname -n`
[ -f $HOME/.keychain/$HOSTNAME-sh ] && \
        . $HOME/.keychain/$HOSTNAME-sh
[ -f $HOME/.keychain/$HOSTNAME-sh-gpg ] && \
        . $HOME/.keychain/$HOSTNAME-sh-gpg

zplug load
