export ZPLUG_HOME=$HOME/git-repos/zplug

# Machine specific configuration files
if [ -d $HOME/.zsh_conf ]; then
	for file in $HOME/.zsh_conf/*.zsh; do
		source $file
	done
fi

# Common configuration files
if [ -d $HOME/git-repos/.file/zshrc/ ]; then
	for file in $HOME/git-repos/.file/zshrc/*.zsh; do
		source $file
	done
fi

source $ZPLUG_HOME/init.zsh

zplug "plugins/kubectl", from:oh-my-zsh
zplug "plugins/fzf", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh
zplug "themes/gentoo", from:oh-my-zsh
zplug "~/git-repos/.file/zplug/kube", from:local, defer:3
zplug "~/git-repos/.file/zplug/linux", from:local, if:"[[ $OSTYPE == *linux* ]]" 
zplug "seebi/dircolors-solarized"
zplug "changyuheng/fz", defer:1
zplug "rupa/z", use:z.sh

ulimit -n 4096

[ -z "$SSH_TTY" ] && keychain id_rsa -q
[ -z "$HOSTNAME" ] && HOSTNAME=`uname -n`
[ -f $HOME/.keychain/$HOSTNAME-sh ] && \
        . $HOME/.keychain/$HOSTNAME-sh
[ -f $HOME/.keychain/$HOSTNAME-sh-gpg ] && \
        . $HOME/.keychain/$HOSTNAME-sh-gpg

zplug load
